version: '3'

services:

    # db:
    #     image: mysql
    #     command: --default-authentication-plugin=mysql_native_password
    #     restart: always
    #     environment:
    #       MYSQL_ROOT_PASSWORD: example

    # adminer:
    #   image: adminer
    #   restart: always
    #   ports:
    #     - 8080:8080

      

  db:
   image: mysql:5.7
  #  restart: always
   environment:
    MYSQL_USER: me
    MYSQL_PASSWORD: test
    MYSQL_ROOT_PASSWORD: test
    MYSQL_DATABASE: data
   ports:
   - "3306:3306"

  phpmyadmin:
   image: phpmyadmin/phpmyadmin
   restart: always
   links:
   - db
   depends_on:
   - db
   ports:
   - "8080:80"

  apache:
   image: webdevops/php-apache-dev
   restart: always
   volumes:
   - .:/app
   ports:
   - "80:80"
   - "443:443"
   depends_on:
   - db
   links:
   - db

#docker-compose up